{"time":"2025-10-16T21:32:07.0444099+02:00","level":"INFO","msg":"stream: starting","core version":"0.21.1"}
{"time":"2025-10-16T21:32:07.4349685+02:00","level":"INFO","msg":"stream: created new stream","id":"p2tlj1f8"}
{"time":"2025-10-16T21:32:07.4355091+02:00","level":"INFO","msg":"writer: started","stream_id":"p2tlj1f8"}
{"time":"2025-10-16T21:32:07.4355091+02:00","level":"INFO","msg":"stream: started","id":"p2tlj1f8"}
{"time":"2025-10-16T21:32:07.4355091+02:00","level":"INFO","msg":"handler: started","stream_id":"p2tlj1f8"}
{"time":"2025-10-16T21:32:07.4355091+02:00","level":"INFO","msg":"sender: started","stream_id":"p2tlj1f8"}
{"time":"2025-10-16T21:37:38.4809788+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"time":"2025-10-16T22:31:29.4884157+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.179.87:53708->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-16T22:42:40.692712+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
